n1 = int(input("enter number one: "))
n2 = int(input("enter number two: "))
n3 = int(input("enter number three: "))
average = ((n1 + n2 + n3)/3)
print("the average of",n1,n2,'and',n3,"is:",average)
